name: Build the app and push it to the GP branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:

    - name: Checkout this source code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install NODE_MODULES
      run: npm install  --legacy-peer-deps
      
    - name: Build amd Commit files
      run: node build.js
      
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "build version - 1.0.${{github.run_number}}"
